name: run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
    #        volumes:
    #          - ./scripts:./.scripts
    env:
      PGPASSWORD: admin
      CI: true

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Get Postgres Client
        run: |
          sudo apt-get -y install postgresql-client
      - name: Prepare DB for tests
        run: |
          psql -U admin -h localhost -f ./scripts/setupDbAsAdmin.sql
          psql -U admin -d budget -h localhost -f ./scripts/setupBudgetSchemasAsAdmin.sql
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build with Gradle Wrapper
        run: ./gradlew test --scan
